//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.09 at 03:38:14 PM CET 
//


package com.iwom.theatre.apigateway.payment.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.iwom.theatre.apigateway.payment.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FetchPayments_QNAME = new QName("http://service.payment.theatre.iwom.com/", "fetchPayments");
    private final static QName _FetchPaymentsResponse_QNAME = new QName("http://service.payment.theatre.iwom.com/", "fetchPaymentsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.iwom.theatre.apigateway.payment.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FetchPayments }
     * 
     */
    public FetchPayments createFetchPayments() {
        return new FetchPayments();
    }

    /**
     * Create an instance of {@link FetchPaymentsResponse }
     * 
     */
    public FetchPaymentsResponse createFetchPaymentsResponse() {
        return new FetchPaymentsResponse();
    }

    /**
     * Create an instance of {@link PaymentDetails }
     * 
     */
    public PaymentDetails createPaymentDetails() {
        return new PaymentDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FetchPayments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FetchPayments }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.payment.theatre.iwom.com/", name = "fetchPayments")
    public JAXBElement<FetchPayments> createFetchPayments(FetchPayments value) {
        return new JAXBElement<FetchPayments>(_FetchPayments_QNAME, FetchPayments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FetchPaymentsResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FetchPaymentsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://service.payment.theatre.iwom.com/", name = "fetchPaymentsResponse")
    public JAXBElement<FetchPaymentsResponse> createFetchPaymentsResponse(FetchPaymentsResponse value) {
        return new JAXBElement<FetchPaymentsResponse>(_FetchPaymentsResponse_QNAME, FetchPaymentsResponse.class, null, value);
    }

}
